### PR TITLE
Least-privilege for Organization or Account

### PR DESCRIPTION
**Pull request by 0xjjoyy**
Pointer to Least-privilege for Organization or Account using condition context key.

*Issue #, if available:*

*Description of changes:*
Add pointer to inform reader of condition context key for organization and account

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by GitGaby** [comment]
Thanks, 0xjjoyy; nice security consideration.  I'm adding this to the guide.

**Comment by bhouse** [comment]
@GitGaby does this work in practice? I haven't been able to use it successfully.

**Comment by 0xjjoyy** [comment]
@bhouse are you able to share an example policy of what you were trying?

**Comment by bhouse** [comment]
Here's an example I've tried: https://gist.github.com/bhouse/ddfe6727cf57fdafeac246747bb815ac


I've also tried using `aws:SourceAccount` with an account id in the condition, in place of `aws:PrincipalOrgID`, but not found that to work either.

The theory is that cloudtrail is not operating as a part of the member account, so it can't be identified with either the account or org in a condition. We found a similar conclusion for a vpc flow log condition on [reddit](https://www.reddit.com/r/aws/comments/b3zgol/getting_awsprincipalorgid_to_work_with_central/ej3k43b/)

When I remove the condition, CloudTrail writes to the bucket without a problem. It stops working with the condition in the policy.

**Comment by GitGaby** [comment]
@bhouse this might not be the solution, but I looked at the syntax for `aws:PrincipalOrgID` in the [IAM docs](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-principalorgid) and saw that the ID is treated as an array: 

``` 
{
  "Version": "2012-10-17",
  "Statement": {
    "Sid": "AllowPutObject",
    "Effect": "Allow",
    "Principal": "*",
    "Action": "s3:PutObject",
    "Resource": "arn:aws:s3:::policy-ninja-dev/*",
    "Condition": {"StringEquals":
      {"aws:PrincipalOrgID":["o-xxxxxxxxxxx"]}
    }
  }
} 
``` 
Can you let me know if wrapping the org ID value in brackets improves your results? -- Thanks, GitGaby

**Comment by bhouse** [comment]
Thanks for checking into this and I appreciate the responsiveness!

When I specified the value as an array, it didn't change the outcome. Also it appears that the policy formatter will automatically flatten the array when there is only one element in it and remove the brackets.

**Comment by GitGaby** [comment]
AWS Support has confirmed to another user that is not possible to use condition keys like aws:PrincipalOrgId or aws:SourceAccount as the CloudTrail service does not operate within ones AWS account.  I'm removing this step from the documentation.  Thanks to both of you for raising this discussion.

**Pull request merged**
